FROM golang:1.21.0 AS builder

WORKDIR /workspace

COPY golang/. .

ENV GOOS=linux
ENV GOARCH=386
RUN  go build -o full


#FROM alpine:3.16.7
FROM busybox:latest

WORKDIR /app

COPY --from=builder /workspace/full .

CMD ["./full"]