version: '3'

services:
  app:
    tty: true
    build:
      context: .
    command: sleep infinity
    volumes:
      - ./golang:/app
    container_name: golang
    networks:
      - go-network


networks:
  go-network:
    driver: bridge
